version: '2'

services:
    kafka1:
        image: wurstmeister/kafka
        restart: unless-stopped
        container_name: kafka1
        ports:
            - "9093:9092"
        external_links:
            - zoo1
            - zoo2
            - zoo3
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ADVERTISED_HOST_NAME: 10.255.198.111                   ## 修改:宿主机IP
            KAFKA_ADVERTISED_PORT: 9093                                 ## 修改:宿主机映射port
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.255.198.111:9093    ## 绑定发布订阅的端口。修改:宿主机IP
            KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2181,zoo3:2181"

    kafka2:
        image: wurstmeister/kafka
        restart: unless-stopped
        container_name: kafka2
        ports:
            - "9094:9092"
        external_links:
            - zoo1
            - zoo2
            - zoo3
        environment:
            KAFKA_BROKER_ID: 2
            KAFKA_ADVERTISED_HOST_NAME: 10.255.198.111                   ## 修改:宿主机IP
            KAFKA_ADVERTISED_PORT: 9094                                 ## 修改:宿主机映射port
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.255.198.111:9094    ## 绑定发布订阅的端口。修改:宿主机IP
            KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2181,zoo3:2181"    

    kafka3:
        image: wurstmeister/kafka
        restart: unless-stopped
        container_name: kafka3
        ports:
            - "9095:9092"
        external_links:
            - zoo1
            - zoo2
            - zoo3
        environment:
            KAFKA_BROKER_ID: 3
            KAFKA_ADVERTISED_HOST_NAME: 10.255.198.111                   ## 修改:宿主机IP
            KAFKA_ADVERTISED_PORT: 9095                                 ## 修改:宿主机映射port
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.255.198.111:9095    ## 绑定发布订阅的端口。修改:宿主机IP
            KAFKA_ZOOKEEPER_CONNECT: "zoo1:2181,zoo2:2181,zoo3:2181"   

    kafka-manager:
        image: sheepkiller/kafka-manager:latest
        restart: unless-stopped
        container_name: kafka-manager
        hostname: kafka-manager
        ports:
            - "9000:9000"
        links:            # 连接本compose文件创建的container
            - kafka1
            - kafka2
            - kafka3
        external_links:   # 连接本compose文件以外的container
            - zoo1
            - zoo2
            - zoo3
        environment:
            ZK_HOSTS: zoo1:2181,zoo2:2181,zoo3:2181                 ## 修改:宿主机IP
            TZ: CST-8

networks:
    default:
        external:
            name: test_default